### ISSUE TITLE
Pack update not always working as expected

### ISSUE THREAD

**Issue by alexanderjeurissen** [maralla/pack#18]
I've ran multiple times in the scenario where:

1. I update my vim colorscheme that I host on Github
2. I run pack update
3. I browse to the pack directory => `~/.config/nvim/pack`
4. I do a git log and confirm that the latest commit is present
5. I kill all running instances of Vim
6. I run vim, and somehow the latest changes are not present in Vim
7. I pack uninstall the colorscheme
8. I pack install it again
9. I reexecute step 5, but now the changes are persisted.

Could you help me debug where this issue might originate ? Feel free to request any additional information that you need.

**Comment by alexanderjeurissen** [comment]
@maralla Did you get a chance to look at the issue I've reported above ? It's still ocurring on the regular and the only workaround so far is to constantly reinstall a plugin to get it to update the plugin correctly.

My first hunch is that currently the repository is only fetched, but never rebased on the remote. Or that currently pack doesn't handle git pulls that require a recursive merge strategy.

**Comment by alexanderjeurissen** [comment]
Ok I checked, and it seems that after pack update when navigating to `$pack_path/colorschemes/start/lumiere.vim` that executing git log shows the latest commit being present in the git repository.

So this rules out that it's a git fetch or pull issue, it seems that neovim doesn't pick up on the changes, but it does pick up on the changes when reinstalling the plugin 🤔

**Comment by maralla** [comment]
The commit 93b1e52309b0f0467681170390ca4b7bec4b08a7 fixed the problem. And a new version will be released. Please update.

**Comment by alexanderjeurissen** [comment]
yes this issue has since been resolved.
