### ISSUE TITLE
Accidently run `pack install`, which empties my .packfile

### ISSUE THREAD

**Issue by gou4shi1** [maralla/pack#25]
(On ubuntu 16.04 vim 8.1)

Before that, I have install many plugins
Accidently, I run `pack install`
(this command shows something like that:
```
 [Chiel92/vim-autoformat] Plugin already installed under "/home/gou4shi1/.vim/pack/formatting/start/vim-autoformat"
```
and then I found that `~/.vim/.pack/packfile` goes empty 

Can I recovery it?

**Comment by gou4shi1** [comment]
I find that if I install a installed plugin, this plugin will be removed from `packfile`

**Comment by fugokidi** [comment]
@gou4shi1 it happened to me as well, can you recover it?

**Comment by alexanderjeurissen** [comment]
@gou4shi1 @fugokidi 

Tl;DR Running `pack generate` should resolve the issue. 

Why?: It seems that pack install clears the pack file, but if you take a closer look the plugins are still present in the `.pack` folder. `pack generate` regerenates the pack file based on the installed plugins.

**Comment by gou4shi1** [comment]
@alexanderjeurissen `pack generate` will not generate `.pack/packfile`

**Comment by maralla** [comment]
You can upgrade to the latest version to resolve the problem.

**Comment by gou4shi1** [comment]
@maralla work like a charm
