### ISSUE TITLE
`pack config` fail on fedora

### ISSUE THREAD

**Issue by gou4shi1** [maralla/pack#27]
On fedora 27, I install pack by `cargo install --git https://github.com/maralla/pack.git`
Something likes `pack list` works.
But `pack config xxx/yyy` fail:
It echo: `entity not found`

**Comment by gou4shi1** [comment]
It seems works.

**Comment by bartlibert** [comment]
For any people who get here and get frustrated because there is no solution in this issue: for me it was solved by setting my "EDITOR" environment variable (e.g. `export EDITOR=vim`)
