### ISSUE TITLE
Cargo.lock not up to date

### ISSUE THREAD

**Issue by bartlibert** [maralla/pack#44]
Hi, I am trying to make a PKGBUILD to get this into the Arch User Repository, but I get an error when trying to build with "cargo build --locked". 
The reason for this is that the Cargo.lock file still contains a reference to version 0.2.3 of this package, while it should be 0.2.5. I can patch this of course, but it would be nice if it was fixed upstream.

**Comment by maralla** [comment]
Thanks for reporting!

**Comment by maralla** [comment]
Fixed in 0dda2025f617192f067dab651698671fb16b6c81.
