### ISSUE TITLE
`CURL_OPENSSL_3' not found

### ISSUE THREAD

**Issue by TerminalWitchcraft** [maralla/pack#7]
I tried installing pack from the releases page(v 0.2.0). When I run the `pack` command, I get the following error:
`./pack: /usr/lib/libcurl.so.4: version 'CURL_OPENSSL_3' not found (required by ./pack)`

Following [this](https://github.com/citra-emu/citra/issues/2976) thread and [this](https://github.com/baumgarr/nixnote2/issues/245) one, I tried this workaround:
`export LD_PRELOAD=/usr/lib/libcurl.so.3`
which finally worked with an error:
`./pack: /usr/lib/libcurl.so.3: no version information available (required by ./pack)`

Is there any way to suppress/rectify this error?

My system information:
Arch Linux 4.13.12-1 x86_64

**Comment by maralla** [comment]
I just released v0.2.1 which should fix the problem.

**Comment by TerminalWitchcraft** [comment]
Thanks! I was able to solve this problem by compiling from source on the previous version. Anyways, I'll upgrade to the latest version.
